<?php

return [
    'INPUT_ERROR_REQUIRED' => '入力必須の項目です。(ERROR_INPUT_REQUIRED)',
    'INPUT_ERROR_LENGTH' => '入力文字数が不正です。(INPUT_ERROR_LENGTH)',
    'INPUT_ERROR_ILLEGAL' => '入力内容が指定されたものではありません。(INPUT_ERROR_ILLEGAL)',
    'INPUT_ERROR_EMAIL_FORMAT' => 'メールアドレスの形式ではありません。(INPUT_ERROR_EMAIL_FORMAT)',
    'INPUT_ERROR_EMAIL_REGISTERED' => 'メールアドレスがすでに登録済みです。(INPUT_ERROR_EMAIL_REGISTERED)',
    'UNAUTHORIZED_ERROR_EMAIL' => 'アカウントが登録されていません。(UNAUTHORIZED_ERROR_EMAIL)',
    'UNAUTHORIZED_ERROR_PASSWORD' => 'パスワードが異なります。(UNAUTHORIZED_ERROR_PASSWORD)',
    'UNAUTHORIZED_ERROR_USER' => '使用できないアカウントです。(UNAUTHORIZED_ERROR_USER)',
    'UNAUTHORIZED_ERROR_NOTAUTH' => '認証が必要です。(UNAUTHORIZED_ERROR_NOTAUTH)',
    'SEND_ERROR_EMAIL' => 'メールの送信に失敗しました。メールアドレスを確認の上再度登録ください。(SEND_ERROR_EMAIL)',
    'VERIFICATION_ERROR_USER' => '認証が必要なアカウントではありません。(VERIFICATION_ERROR_USER)',
    'VERIFICATION_ERROR_TOKEN' => '認証の有効期限が切れています。再度ユーザの登録をお願いします。(VERIFICATION_ERROR_TOKEN)',
    'PASSWORD_RESET_ERROR_TOKEN' => 'パスワード変更の有効期限が切れています。再度登録をお願いします。(PASSWORD_RESET_ERROR_TOKEN)',
];
